# Generated by Django 5.2.7 on 2025-12-14 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pump',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('hp', models.FloatField()),
                ('min_depth', models.IntegerField()),
                ('max_depth', models.IntegerField()),
                ('usage_type', models.CharField(choices=[('home', 'Home'), ('agriculture', 'Agriculture'), ('industry', 'Industry')], max_length=20)),
                ('phase', models.CharField(choices=[('single', 'Single Phase'), ('three', 'Three Phase')], max_length=20)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
