# Generated by Django 5.2.7 on 2025-12-14 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_pump'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pump',
            old_name='hp',
            new_name='horsepower',
        ),
        migrations.AlterField(
            model_name='pump',
            name='phase',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='pump',
            name='usage_type',
            field=models.CharField(max_length=50),
        ),
    ]
