# Generated by Django 5.2.7 on 2025-12-22 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_order_payment_method_order_payment_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='max_depth_ft',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='max_flow_lpm',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='max_head_m',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='motor_power_hp',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='phase',
            field=models.CharField(blank=True, choices=[('single', 'Single Phase'), ('three', 'Three Phase')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='usage_type',
            field=models.CharField(blank=True, choices=[('domestic', 'Domestic'), ('agriculture', 'Agriculture'), ('industrial', 'Industrial')], max_length=20, null=True),
        ),
    ]
